name: lowell_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.1
  - pandas
  - matplotlib
  - python-dotenv 
  - pip
  - sqlite
  - requests
  - beautifulsoup4
  - openai 
  - panel 
  - watchfiles 
  - pip:
      - pymupdf

