name: ocr_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.1
  - pandas
  - scikit-learn
  - pytesseract
  - scikit-image
  - pillow
  - opencv
  - matplotlib
  - python-dotenv # note to me: might be pip, install and recheck for this 
  - pip
  - pip:
      - openai
      - keras-ocr==0.9.3
      - easyocr==1.7.2
      - tensorflow==2.15.1
